/* ================================================
   KAIROS CREATIVE — PRODUCT DATA
   Modify this file to update all product info
   ================================================ */

const PRODUCTS = [
  {
    id: 'cuaderno-b5',
    category: 'cuaderno',
    name: 'Cuaderno B5',
    tagline: 'Nuestro formato más generoso para quienes escriben sin límites.',
    badge: 'B5',
    image: 'assets/products/cuaderno-b5.jpg',
    color: '#1a3d5c',
    shape: 'notebook', // for 3D viewer
    specs: {
      'Ancho': '17 cm',
      'Alto': '22 cm',
      'Hojas': '80 hojas / 160 páginas',
      'Papel': '75 g/m²',
      'Argollado': 'Costado izquierdo',
      'Cubierta': 'Cartulina laminada',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Portada personalizada' },
      { icon: 'fa-solid fa-layer-group', text: 'Contraportada personalizada' },
      { icon: 'fa-regular fa-calendar', text: 'Calendario incluido (Premium)' },
      { icon: 'fa-solid fa-pen-nib', text: 'Hojas internas personalizadas (Premium)' },
      { icon: 'fa-solid fa-boxes-stacked', text: 'Disponible desde 1 unidad' },
    ],
    tags: ['Personalizado', 'Argollado lateral', 'Premium'],
    gallery: [
      'assets/products/cuaderno-b5.jpg',
      'assets/products/cuaderno-a5.jpg',
      'assets/products/cuaderno-a6.jpg',
    ],
  },
  {
    id: 'cuaderno-a5',
    category: 'cuaderno',
    name: 'Cuaderno A5',
    tagline: 'El compañero perfecto para el día a día, ligero y elegante.',
    badge: 'A5',
    image: 'assets/products/cuaderno-a5.jpg',
    color: '#1a5276',
    shape: 'notebook',
    specs: {
      'Ancho': '14 cm',
      'Alto': '22 cm',
      'Hojas': '80 hojas / 160 páginas',
      'Papel': '75 g/m²',
      'Argollado': 'Costado izquierdo',
      'Cubierta': 'Cartulina laminada',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Portada personalizada' },
      { icon: 'fa-solid fa-layer-group', text: 'Contraportada personalizada' },
      { icon: 'fa-regular fa-calendar', text: 'Calendario incluido (Premium)' },
      { icon: 'fa-solid fa-pen-nib', text: 'Hojas internas personalizadas (Premium)' },
      { icon: 'fa-solid fa-boxes-stacked', text: 'Disponible desde 1 unidad' },
    ],
    tags: ['Estándar', 'Premium', 'Marca propia'],
    gallery: [
      'assets/products/cuaderno-a5.jpg',
      'assets/products/cuaderno-b5.jpg',
      'assets/products/cuaderno-a6.jpg',
    ],
  },
  {
    id: 'cuaderno-a6-lateral',
    category: 'cuaderno',
    name: 'Cuaderno A6 Lateral',
    tagline: 'Compacto y práctico, ideal para llevar a todas partes.',
    badge: 'A6',
    image: 'assets/products/cuaderno-a6.jpg',
    color: '#0e3d5c',
    shape: 'notebook',
    specs: {
      'Ancho': '11 cm',
      'Alto': '14 cm',
      'Hojas': '60 hojas / 120 páginas',
      'Papel': '75 g/m²',
      'Argollado': 'Costado izquierdo',
      'Cubierta': 'Cartulina laminada',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Portada personalizada' },
      { icon: 'fa-solid fa-layer-group', text: 'Contraportada personalizada' },
      { icon: 'fa-solid fa-boxes-stacked', text: 'Disponible desde 1 unidad' },
    ],
    tags: ['Argollado lateral', 'Compacto'],
    gallery: [
      'assets/products/cuaderno-a6.jpg',
      'assets/products/cuaderno-a7.jpg',
      'assets/products/cuaderno-a5.jpg',
    ],
  },
  {
    id: 'cuaderno-a6-superior',
    category: 'cuaderno',
    name: 'Cuaderno A6 Superior',
    tagline: 'Estilo bloc de notas, ideal para escritorios y reuniones.',
    badge: 'A6',
    image: 'assets/products/cuaderno-a6.jpg',
    color: '#154360',
    shape: 'notebook',
    specs: {
      'Ancho': '11 cm',
      'Alto': '14 cm',
      'Hojas': '60 hojas / 120 páginas',
      'Papel': '75 g/m²',
      'Argollado': 'Parte superior',
      'Cubierta': 'Cartulina laminada',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Portada personalizada' },
      { icon: 'fa-solid fa-layer-group', text: 'Contraportada personalizada' },
      { icon: 'fa-solid fa-boxes-stacked', text: 'Disponible desde 1 unidad' },
    ],
    tags: ['Argollado superior', 'Bloc de notas'],
    gallery: [
      'assets/products/cuaderno-a6.jpg',
      'assets/products/cuaderno-a5.jpg',
      'assets/products/cuaderno-a7.jpg',
    ],
  },
  {
    id: 'cuaderno-a7',
    category: 'cuaderno',
    name: 'Mini Cuaderno A7',
    tagline: 'El más pequeño de la familia. Grande en personalidad.',
    badge: 'A7',
    image: 'assets/products/cuaderno-a7.jpg',
    color: '#1a2980',
    shape: 'notebook',
    specs: {
      'Ancho': '5.5 cm',
      'Alto': '7 cm',
      'Hojas': '40 hojas / 80 páginas',
      'Papel': '75 g/m²',
      'Argollado': 'Costado',
      'Cubierta': 'Cartulina laminada',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Portada personalizada' },
      { icon: 'fa-solid fa-gift', text: 'Ideal para kit de regalo' },
      { icon: 'fa-solid fa-boxes-stacked', text: 'Disponible desde 1 unidad' },
    ],
    tags: ['Mini formato', 'Regalo ideal'],
    gallery: [
      'assets/products/cuaderno-a7.jpg',
      'assets/products/cuaderno-a6.jpg',
      'assets/products/kit-regalo.jpg',
    ],
  },
  {
    id: 'calendario-premium',
    category: 'calendario',
    name: 'Calendario Premium',
    tagline: 'Diseño de escritorio personalizado para empresas y ocasiones especiales.',
    badge: 'Premium',
    image: 'assets/products/calendario-premium.jpg',
    color: '#2c3e50',
    shape: 'calendar',
    specs: {
      'Formato': 'Escritorio',
      'Meses': '12 meses + portada',
      'Argollado': 'Parte superior',
      'Impresión': 'Full color',
      'Base': 'Incluida',
      'Tipo': 'Personalizado',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Diseño personalizado mes a mes' },
      { icon: 'fa-solid fa-building', text: 'Ideal para regalo corporativo' },
      { icon: 'fa-solid fa-palette', text: 'Colores y branding propios' },
      { icon: 'fa-solid fa-boxes-stacked', text: 'Disponible desde 1 unidad' },
    ],
    tags: ['Corporativo', 'Full color', 'Personalizado'],
    gallery: [
      'assets/products/calendario-premium.jpg',
      'assets/products/calendario-sencillo.jpg',
      'assets/products/kit-regalo.jpg',
    ],
  },
  {
    id: 'calendario-sencillo',
    category: 'calendario',
    name: 'Calendario Sencillo',
    tagline: 'Funcional y accesible, con el sello artesanal de Kairos.',
    badge: 'Básico',
    image: 'assets/products/calendario-sencillo.jpg',
    color: '#1a374d',
    shape: 'calendar',
    specs: {
      'Formato': 'Escritorio',
      'Meses': '12 meses + portada',
      'Argollado': 'Parte superior',
      'Impresión': 'Full color',
      'Base': 'No incluida',
      'Tipo': 'Estándar',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Portada personalizable' },
      { icon: 'fa-solid fa-tag', text: 'Opción más económica' },
      { icon: 'fa-solid fa-boxes-stacked', text: 'Disponible desde 1 unidad' },
    ],
    tags: ['Económico', 'Funcional'],
    gallery: [
      'assets/products/calendario-sencillo.jpg',
      'assets/products/calendario-premium.jpg',
      'assets/products/cuaderno-a5.jpg',
    ],
  },
  {
    id: 'separadores',
    category: 'otros',
    name: 'Separadores',
    tagline: 'Marcapáginas artesanales que convierten la lectura en una experiencia.',
    badge: null,
    image: 'assets/products/separadores.jpg',
    color: '#4a1942',
    shape: 'flat',
    specs: {
      'Alto': '18 cm',
      'Ancho': '5.5 cm',
      'Material': 'Cartulina premium',
      'Impresión': 'Full color',
      'Acabado': 'Laminado brillante',
      'Tipo': 'Personalizado',
    },
    options: [
      { icon: 'fa-solid fa-image', text: 'Diseño personalizado' },
      { icon: 'fa-solid fa-quote-right', text: 'Texto o frase especial' },
      { icon: 'fa-solid fa-gift', text: 'Ideal para kits de regalo' },
    ],
    tags: ['Artesanal', 'Personalizado', 'Regalo'],
    gallery: [
      'assets/products/separadores.jpg',
      'assets/products/kit-regalo.jpg',
      'assets/products/cuaderno-a5.jpg',
    ],
  },
  {
    id: 'lapicero',
    category: 'otros',
    name: 'Lapicero Personalizado',
    tagline: 'El complemento perfecto para tu papelería. Detalles que marcan diferencia.',
    badge: null,
    image: 'assets/products/lapicero.jpg',
    color: '#0f3460',
    shape: 'pen',
    specs: {
      'Longitud': '14 cm',
      'Material': 'Plástico de alta calidad',
      'Impresión': 'Grabado / sublimación',
      'Tinta': 'Azul / Negro',
      'Acabado': 'Brillante o mate',
      'Tipo': 'Personalizado',
    },
    options: [
      { icon: 'fa-solid fa-pen', text: 'Grabado con nombre o logo' },
      { icon: 'fa-solid fa-building', text: 'Ideal para empresas' },
      { icon: 'fa-solid fa-gift', text: 'Perfecto en kit de regalo' },
    ],
    tags: ['Corporativo', 'Kit regalo'],
    gallery: [
      'assets/products/lapicero.jpg',
      'assets/products/kit-regalo.jpg',
      'assets/products/cuaderno-a5.jpg',
    ],
  },
];
